version: '3'

services:
  neovim:
    container_name: neovim
    image: rnkoaa/neovim
    # build:
    #   context: .
    stdin_open: true
    tty: true
    volumes:
      - ./config:/home/neovim/.config


