version: '3'

services:
  neovim:
    container_name: neovim
    image: rnkoaa/neovim
    # build:
    #   context: .
    stdin_open: true
    tty: true
    # user: 999
    volumes:
      - ./config:/home/neovim/.config
      - ./local:/home/neovim/.local


